CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    photo_url VARCHAR(255),
    age INTEGER NOT NULL,
    role VARCHAR(255) NOT NULL
);

CREATE TABLE sport (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE region (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL
);

CREATE INDEX idx_region_name ON region (name);

CREATE TABLE trainer_profile (
    user_id BIGINT PRIMARY KEY,
    bio VARCHAR(1000),
    experience_years INTEGER,
    sport_id BIGINT NOT NULL,
    CONSTRAINT fk_trainer_profile_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_trainer_profile_sport
        FOREIGN KEY (sport_id) REFERENCES sport (id)
);

CREATE TABLE user_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    region_id BIGINT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_user_location_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_location_region
        FOREIGN KEY (region_id) REFERENCES region (id)
);

CREATE TABLE training_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id BIGINT NOT NULL,
    sport_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    version BIGINT NOT NULL,
    location_name VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    start_time TIME(0) WITHOUT TIME ZONE NOT NULL,
    duration_minutes INTEGER NOT NULL,
    max_participants INTEGER NOT NULL,
    current_participants INTEGER NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_training_session_trainer
        FOREIGN KEY (trainer_id) REFERENCES users (id),
    CONSTRAINT fk_training_session_sport
        FOREIGN KEY (sport_id) REFERENCES sport (id)
);

CREATE TABLE training_session_days (
    session_id BIGINT NOT NULL,
    day VARCHAR(255) NOT NULL,
    PRIMARY KEY (session_id, day),
    CONSTRAINT fk_training_session_days_session
        FOREIGN KEY (session_id) REFERENCES training_session (id)
);

CREATE TABLE booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    booked_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT fk_booking_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_booking_session
        FOREIGN KEY (session_id) REFERENCES training_session (id)
);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(512) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);
