ALTER TABLE training_session
    ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'SCHEDULED';

ALTER TABLE training_session
    ADD COLUMN updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE training_session
    ADD COLUMN cancelled_at TIMESTAMP(6) WITHOUT TIME ZONE;

ALTER TABLE training_session
    ADD CONSTRAINT chk_training_session_status
    CHECK (status IN ('SCHEDULED', 'CANCELLED', 'COMPLETED'));

CREATE INDEX idx_training_session_status_start_date
    ON training_session (status, start_date);

CREATE TABLE user_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_user_notification_recipient
        FOREIGN KEY (recipient_id) REFERENCES users (id),
    CONSTRAINT chk_user_notification_type
        CHECK (type IN ('SESSION_UPDATED', 'SESSION_CANCELLED'))
);

CREATE INDEX idx_user_notification_recipient_created
    ON user_notification (recipient_id, created_at DESC);
