services:
  

  redis:

    image: redis:7.4

    container_name: csports-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:

    image: postgis/postgis:17-3.5

    container_name: csports-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: csports
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


